apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: illumni-app
  labels:
    app: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: illumni-app
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: illumni-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: illumni-app
data:
  fluent.conf: |
    <source>
      @type tail
      format json
      path "/var/log/containers/illumni*.log"
      pos_file "/var/log/illumni.log.pos"
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag "illumni.*"
    </source>

    <match **>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      verify_es_version_at_startup false
      max_retry_get_es_version 1
      max_retry_putting_template 1
    </match>
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: illumni-app
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.7-debian-elasticsearch6-2
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-client.backoffice.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
          - name: FLUENT_ELASTICSEARCH_SED_DISABLE
            value: "true"
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config

